require 'rake'

# Defaults
task :default => [:spec]
command = 'lib/jspec/bin/jspec'
subcommand = 'run'
paths = '-p src/**/*.js,site/**/*.js,spec/**/*.js,Rakefile'

desc 'Install dependencies'
task :install => ['site/javascripts/jquery.min.js',
                  'site/javascripts/swfobject.js'] do
  # wget missing files
end

desc 'Continuously monitor code'
task :bind => [:dobind, :spec]
task :dobind do
  subcommand = 'bind --actions "rake build"'
end

desc 'Run in rhino'
task :rhino => [:dorhino, :spec]
task :dorhino do
  subcommand = 'run --rhino'
end

desc 'Check specs'
task :spec => [:install, :build] do
  sh "#{command} #{subcommand} #{paths}"
end

multitask :build => ['site/index.html',
                     'spec/all.js',
                     'site/javascripts/playerground.js']

file 'site/index.html' => FileList['src/**/*.haml', 'src/**/*.sass'] do
  sh "staticmatic build ."
end

file 'site/javascripts/playerground.js' => FileList['src/js/**/*.js'] do
  # Compile playerground.js
  sh "src/compile.rb"
end

# Generates all.js files
file 'spec/all.js' => FileList['spec/**/*spec.js'] do
  # Add 'spec/**' to recursively build all.js files.
  Dir['spec'].each do |d|
    gen_all d if File.directory? d
  end
end

def gen_all dir
  puts "Generating #{dir}"
  File.open(File.join(dir, '/all.js'), 'w') do |file|
    file.puts '// This file is automatically generated with `rake spec`.'
    file.puts 'JSpec'
    FileList[File.join(dir, '/**/*spec.js')].each do |spec|
      # Remove leading 'spec/'
      file.puts(".exec(BASE + '%s')" % spec.sub('spec/', ''))
    end
  end
end
