// This file is automatically generated with `rake spec`.
JSpec
.exec(BASE + 'base/jquery.spec.js')
.exec(BASE + 'base/pure.spec.js')
.exec(BASE + 'base/spec.spec.js')
.exec(BASE + 'lib/taggedsets.spec.js')
