// This file is automatically generated with `rake spec`.
JSpec
.exec(BASE + 'base/jquery.spec')
.exec(BASE + 'base/pure.spec')
.exec(BASE + 'base/spec.spec')
.exec(BASE + 'lib/proplist.spec')
.exec(BASE + 'lib/taggedsets.spec')
